siteName: Car Pro App
productionUrl: https://www.car-pro.app
languages:
  - code: fr
    status: published
    keepUrlPrefix: false
    name: Français
    isWebsiteDefault: true
collections: []
newTabLinkTypes:
  - external